version: '3.7'

volumes:
  data_certs:
  data_vhost:
  data_html:
  data_archive:
    driver: local
    driver_opts:
      type: nfs
      o: nfsvers=4,addr=beta.bioatlas.se,rw
      device: ":/mnt/extvol/nfs/data/data_archive"

services:

#https://forums.docker.com/t/docker-failing-to-correctly-process-valid-yaml-config/183/4
  sftp:
    privileged: true
    image: atmoz/sftp:alpine
    volumes:
      - ./ftpusers.conf:/etc/sftp/users.conf:ro
      - data_archive:/home/dyntaxa/
    ports:
      - "2222:22"

  webserver:
    image: nginx:alpine
    init: true
    volumes:
      - ./app.conf:/etc/nginx/conf.d/default.conf
      - data_archive:/usr/share/nginx/html:ro
    environment:
      - VIRTUAL_HOST=archive.infrabas.se
      - LETSENCRYPT_HOST=archive.infrabas.se
      - LETSENCRYPT_EMAIL=roger@bioatlas.se
    depends_on:
      - sftp
      - minio
      
  minio:
    image: minio/minio:RELEASE.2019-04-23T23-50-36Z
    volumes:
     - data_archive:/data
    env_file: ./env/.envminio
    environment:
      - VIRTUAL_HOST=minio.infrabas.se
      - VIRTUAL_PORT=9000
      - LETSENCRYPT_HOST=minio.infrabas.se
      - LETSENCRYPT_EMAIL=roger@bioatlas.se
    command: server /data

  cron:
    image: alpine
    volumes:
      - data_archive:/data
      - ./get_dyntaxa:/etc/periodic/hourly/get_dyntaxa
    command: crond -c /etc/crontabs -S -f

  mc:
    image: minio/mc
    env_file: ./env/.envminio
    depends_on:
      - minio

networks:
  default:
    external:
      name: nextcloud-docker_default

